name: CI
on:
  pull_request:
  push:
    branches: [main, staging]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ # frontend root
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 'lts/*', cache: 'npm' }
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build
